baseURL: https://bajtos.net/
languageCode: en-us
title: Miroslav Bajtoš
disableKinds:
  - taxonomy
  - taxonomyTerm
markup:
  highlight:
    style: autumn
author:
  name: Miroslav Bajtoš
params:
  dateForm: 'January 2, 2006'
  dateformShort: 'Jan 2'
  dateformNumTime: '2006-01-02 15:04 CET'
